---
config:
  templates: ["templates", "../../flatstep/templates"]
  static_url: "/"
  cache: False

meta:
  author: "Claudio Driussi"
  generator: "Almoststatic"

site_name: Start Bootstrap
slogan: An <a href="https://pypi.org/project/almoststatic/">Almoststatic</a> theme

MainMenu:
  - name: About
    url: index#about

  - name: Projects
    url: index#projects

  - name: Contact
    url: index#signup

  - name: Info...
    url: info
